import { CompanySettings, Property } from './types';

export const defaultCompanySettings: CompanySettings = {
  companyName: 'SUN REALTORS',
  tagline: 'Finding The Right Place For You',
  regNumber: 'TNRERA / 2024 / SUN / 05333',
  logoUrl: '',
  contactPerson: 'Suresh Kumar P G (Managing Director)',
  phone: '+91 98941 05333',
  whatsapp: '+91 99427 05333',
  email: 'sunrealtorsindia@gmail.com',
  website: 'www.sunrealtorsindia.com',
  address: '814 RKM Complex, Lakshminagar',
  cityStateZip: 'Erode – 638316, Tamil Nadu',
  disclaimerText:
    'Disclaimer: The details provided herein are based on information furnished by the property owner/vendor and physical verification conducted by SUN REALTORS. Buyers are advised to verify documents and legal titles independently prior to transaction. SUN REALTORS holds no liability for discrepancies. Contact: sunrealtorsindia@gmail.com | +91 98941 05333 | www.sunrealtorsindia.com',
  themePrimaryColor: '#1A2455',
  themeAccentColor: '#F0A500',
};

export const sampleProperties: Property[] = [
  {
    id: 'prop-001',
    status: 'Active',
    version: 1,
    createdAt: '2026-08-10T10:30:00Z',
    updatedAt: '2026-08-15T14:20:00Z',
    identification: {
      refNo: 'SUN-PR-2026-001',
      date: '2026-08-10',
      propertyName: 'Green Acres Commercial Plot',
      location: 'NH-44 Bypass Road, Hosur',
      village: 'Zuzuvadi',
      taluk: 'Hosur',
      district: 'Krishnagiri',
      state: 'Tamil Nadu',
      surveyNo: '142/2B',
      subDivisionNo: '3A',
      propertyType: 'Commercial',
    },
    siteDetails: {
      totalExtent: '2.5 Acres (108,900 Sq.Ft)',
      areaForSale: '2.5 Acres',
      landAreaUnit: 'Acres',
      facing: 'North-East',
      roadAccess: 'Yes',
      roadWidth: '80 feet',
      roadFrontage: '220 feet',
      plotDimensions: '220 x 495 ft',
      landLevel: 'On Road Level',
      currentUse: 'Vacant Commercial Plot',
      existingStructure: 'Vacant Land',
      boundaryWall: 'Yes',
      waterSource: 'Yes',
      electricitySupply: 'Yes',
      northBoundary: '80ft NH-44 Service Road',
      southBoundary: 'Private Commercial Property',
      eastBoundary: 'Proposed 40ft Internal Road',
      westBoundary: 'Survey No. 142/1',
    },
    locationAccess: {
      googleMapsUrl: 'https://maps.google.com/?q=12.7401,77.8253',
      streetViewUrl: 'https://maps.google.com/?q=12.7401,77.8253&cbp=12',
      distMainRoad: 'Directly on Service Road',
      distHighway: '0.1 km (NH-44)',
      distNearestTown: '3.5 km (Hosur Town Center)',
      distRailway: '4.8 km (Hosur Station)',
      distAirport: '45 km (Bengaluru International Airport)',
      distSchoolCollege: '1.2 km (Adhiyamaan Engg College)',
      distHospital: '2.0 km (Kauvery Hospital)',
      otherLandmark: 'Opposite Sipcot Industrial Complex Phase 1',
    },
    ownership: {
      currentOwner: 'M/s Sunder Infra Developers Pvt Ltd',
      titleDeedStatus: 'Clear Title',
      parentDocs: 'Available',
      encumbranceCertificate: 'Up to Date',
      landTaxReceipt: 'Paid Up to Date',
      possessionCertificate: 'Available',
      surveySketch: 'Available',
      taxDetails: 'Assessment No. 892/2025-26 Paid up to March 2027',
      zoningClassification: 'Commercial Heavy Zone (DTCP Approved)',
      otherApprovals: 'DTCP Approval No. 144/2023, Fire & Pollution NOC Available',
    },
    salePricing: {
      areaOffered: '2.5 Acres',
      negotiable: 'Yes',
      ratePerUnit: '₹ 1,850 per Sq.Ft',
      totalAskingPrice: '₹ 20,14,65,000',
      paymentTerms: '20% Booking Advance, Balance on Registration within 45 Days',
      advanceBookingAmount: '₹ 40,00,000',
      expectedRegistrationDate: '2026-10-15',
    },
    features: {
      additionalHighlights:
        'Prime Highway frontage with 80ft main road access. Ideal for Commercial Complex, Logistics Hub, Auto Showroom or IT Tech Park. Corner property with dual road frontage and high visibility.',
    },
    sitePlan: {
      sitePlanImageUrl: '',
      notes: 'DTCP Approved Plot Layout Plan attached with clear boundaries.',
    },
    contact: {
      companyName: 'SUN REALTORS',
      contactPerson: 'K. Sunder Raman',
      mobileWhatsApp: '+91 98400 12345',
      email: 'sunder@sunrealtors.in',
      officeAddress: 'No. 45, Sun Towers, Guindy, Chennai - 600032',
    },
  },
  {
    id: 'prop-002',
    status: 'Active',
    version: 2,
    createdAt: '2026-08-18T09:15:00Z',
    updatedAt: '2026-08-28T16:45:00Z',
    identification: {
      refNo: 'SUN-PR-2026-002',
      date: '2026-08-18',
      propertyName: 'Sun Vista Residential Gated Plot',
      location: 'ECR Main Road, Kovalam',
      village: 'Kovalam',
      taluk: 'Thiruporur',
      district: 'Chengalpattu',
      state: 'Tamil Nadu',
      surveyNo: '88/4',
      subDivisionNo: '1C',
      propertyType: 'Residential',
    },
    siteDetails: {
      totalExtent: '24 Cents (10,452 Sq.Ft)',
      areaForSale: '24 Cents',
      landAreaUnit: 'Cents',
      facing: 'East',
      roadAccess: 'Yes',
      roadWidth: '40 feet',
      roadFrontage: '75 feet',
      plotDimensions: '75 x 139 ft',
      landLevel: 'Above Road Level',
      currentUse: 'Gated Residential Plot',
      existingStructure: 'Vacant Land',
      boundaryWall: 'Yes',
      waterSource: 'Yes',
      electricitySupply: 'Yes',
      northBoundary: 'Plot No. 12',
      southBoundary: '40ft Layout Road',
      eastBoundary: 'ECR Service Channel',
      westBoundary: 'Plot No. 15',
    },
    locationAccess: {
      googleMapsUrl: 'https://maps.google.com/?q=12.7885,80.2492',
      streetViewUrl: '',
      distMainRoad: 'Directly on ECR Main Road',
      distHighway: 'Direct access to East Coast Road',
      distNearestTown: '6 km (Mahabalipuram)',
      distRailway: '18 km (Chengalpattu Junction)',
      distAirport: '38 km (Chennai International Airport)',
      distSchoolCollege: '2.5 km (Chettinad Sarvaloka Education)',
      distHospital: '4.0 km (Praveena Hospital)',
      otherLandmark: '500 meters from Kovalam Beach Resort',
    },
    ownership: {
      currentOwner: 'R. Meenakshi & S. Rajesh',
      titleDeedStatus: 'Clear Title',
      parentDocs: 'Available',
      encumbranceCertificate: 'Up to Date',
      landTaxReceipt: 'Paid Up to Date',
      possessionCertificate: 'Available',
      surveySketch: 'Available',
      taxDetails: 'Panchayat Tax Paid up to 2026',
      zoningClassification: 'CRZ Approved Residential Zone',
      otherApprovals: 'CMDA / Local Body Approved Layout',
    },
    salePricing: {
      areaOffered: '24 Cents',
      negotiable: 'No',
      ratePerUnit: '₹ 28,00,000 per Cent',
      totalAskingPrice: '₹ 6,72,00,000',
      paymentTerms: '10% Advance, Balance on final deed execution',
      advanceBookingAmount: '₹ 15,00,000',
      expectedRegistrationDate: '2026-09-30',
    },
    features: {
      additionalHighlights:
        'Premium sea-facing residential plot in prestigious ECR enclave. 24/7 security, underground cabling, avenue trees, clear legal titles. Excellent potential for luxury villa construction.',
    },
    sitePlan: {
      sitePlanImageUrl: '',
      notes: 'Approved CMDA layout blueprint attached.',
    },
    contact: {
      companyName: 'SUN REALTORS',
      contactPerson: 'V. Anand (Senior Property Advisor)',
      mobileWhatsApp: '+91 98400 54321',
      email: 'anand@sunrealtors.in',
      officeAddress: 'No. 45, Sun Towers, Guindy, Chennai - 600032',
    },
  },
  {
    id: 'prop-003',
    status: 'Draft',
    version: 1,
    createdAt: '2026-09-01T11:00:00Z',
    updatedAt: '2026-09-01T11:00:00Z',
    identification: {
      refNo: 'SUN-PR-2026-003',
      date: '2026-09-01',
      propertyName: 'Sri Vari Agricultural Farmland',
      location: 'Othakalmandapam, Pollachi Road',
      village: 'Othakalmandapam',
      taluk: 'Madukkarai',
      district: 'Coimbatore',
      state: 'Tamil Nadu',
      surveyNo: '304/1',
      subDivisionNo: '2',
      propertyType: 'Agricultural',
    },
    siteDetails: {
      totalExtent: '8.4 Acres',
      areaForSale: '8.4 Acres',
      landAreaUnit: 'Acres',
      facing: 'South',
      roadAccess: 'Yes',
      roadWidth: '30 feet',
      roadFrontage: '310 feet',
      plotDimensions: '310 x 1180 ft',
      landLevel: 'On Road Level',
      currentUse: 'Coconut & Inter-crop Farming',
      existingStructure: 'Shed / Temporary Structure',
      boundaryWall: 'No',
      waterSource: 'Yes',
      electricitySupply: 'Yes',
      northBoundary: 'Canal Stream',
      southBoundary: '30ft Village Panchayat Road',
      eastBoundary: 'Survey No 304/2',
      westBoundary: 'Government Reserve Forest Edge',
    },
    locationAccess: {
      googleMapsUrl: '',
      streetViewUrl: '',
      distMainRoad: '0.8 km from Pollachi Main Road',
      distHighway: '1.2 km',
      distNearestTown: '12 km (Coimbatore City)',
      distRailway: '14 km (Coimbatore Junction)',
      distAirport: '24 km (Coimbatore International Airport)',
      distSchoolCollege: '3.0 km (Hindusthan College)',
      distHospital: '5.0 km (Karpagam Hospital)',
      otherLandmark: 'Near Malumichampatti Junction',
    },
    ownership: {
      currentOwner: 'P. Shanmugam & Brothers',
      titleDeedStatus: 'Clear Title',
      parentDocs: 'Available',
      encumbranceCertificate: 'Up to Date',
      landTaxReceipt: 'Paid Up to Date',
      possessionCertificate: 'Available',
      surveySketch: 'Available',
      taxDetails: 'Agricultural Tax Exemption / Chitta Adangal Clear',
      zoningClassification: 'Agricultural Zone',
      otherApprovals: 'Free Agriculture Power Connection (5 HP Borewell)',
    },
    salePricing: {
      areaOffered: '8.4 Acres',
      negotiable: 'Yes',
      ratePerUnit: '₹ 85,00,000 per Acre',
      totalAskingPrice: '₹ 7,14,00,000',
      paymentTerms: 'Standard 60 Days Settlement',
      advanceBookingAmount: '₹ 25,00,000',
      expectedRegistrationDate: '2026-11-01',
    },
    features: {
      additionalHighlights:
        'Fertile red soil with 450 yield-bearing coconut trees. 2 high-yield borewells with free electricity connection. Ideal for farmhouses, resort development or organic farming.',
    },
    sitePlan: {
      sitePlanImageUrl: '',
      notes: '',
    },
    contact: {
      companyName: 'SUN REALTORS',
      contactPerson: 'K. Sunder Raman',
      mobileWhatsApp: '+91 98400 12345',
      email: 'sunder@sunrealtors.in',
      officeAddress: 'No. 45, Sun Towers, Guindy, Chennai - 600032',
    },
  },
];
